# -*- coding: utf-8 -*-
"""28. 04 Mar Assign.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vxs4bExSEQFlXSAPG-PnK8PdjqUOhTVe

04 MARCH ASSIGNMENT

1.
"""

import plotly.graph_objects as go

import seaborn as sns

import plotly.express as px

titanic = sns.load_dataset('titanic')
fig = px.scatter(titanic, x='age', y='fare')
fig.show()

"""2."""

import plotly.express as px

tips = px.data.tips()
fig = px.box(tips, x='day', y='total_bill', color='sex')
fig.show()

"""3."""

import plotly.express as px

tips = px.data.tips()
fig = px.histogram(tips, x='sex', y='total_bill', color='day', pattern_shape='smoker',)
fig.show()

"""4."""

iris = px.data.iris()

fig = px.scatter_matrix(iris, dimensions=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], color='species')
fig.show()

"""5.

distplot is a function in the Seaborn library used to plot a histogram and a kernel density estimate (KDE) of a dataset. It provides a convenient way to visualize the distribution of a single variable.
"""

tips = px.data.tips()

fig = px.histogram(tips, x='total_bill', color='sex', opacity=0.7)
fig.show()